### ISSUE TITLE
it's should be its

### ISSUE THREAD

**Issue by robmuh** [whitman-colm/sss#3]

**Comment by tslnc04** [comment]
Try not to comment on that yet, as we know that there is much more than just that. :)

**Comment by whitman-colm** [comment]
shaddup.

**Comment by robmuh** [comment]
Tim that was a test and the issue had already been closed.

*Rob Muhlestein*
@SkilStak <http://twitter.com/skilstak>, Inc.
rob@skilstak.com
704-310-6778
@robmuh <http://twitter.com/robmuh>

**Comment by whitman-colm** [comment]
Actually, if there are any grammatical flaws, please tell me so I can patch it. thanks.
